const mongoose = require("mongoose");

const appDetailsSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, required: true },
  descriptionHTML: { type: String, required: true },
  summary: { type: String, required: true },
  installs: { type: String, required: true },
  minInstalls: { type: Number, required: true },
  maxInstalls: { type: Number, required: true },
  score: { type: Number, required: true },
  scoreText: { type: String, required: true },
  ratings: { type: Number, required: true },
  reviews: { type: Number, required: true },
  histogram: { type: Object, required: true },
  price: { type: Number, required: true },
  free: { type: Boolean, required: true },
  currency: { type: String, required: true },
  priceText: { type: String, required: true },
  available: { type: Boolean, required: true },
  offersIAP: { type: Boolean, required: true },
  IAPRange: { type: String, required: true },
  androidVersion: { type: String, required: true },
  androidVersionText: { type: String, required: true },
  androidMaxVersion: { type: String, required: true },
  developer: { type: String, required: true },
  developerId: { type: String, required: true },
  developerEmail: { type: String, required: true },
  developerWebsite: { type: String, required: true },
  developerAddress: { type: String, required: true },
  privacyPolicy: { type: String, required: true },
  developerInternalID: { type: String, required: true },
  genre: { type: String, required: true },
  genreId: { type: String, required: true },
  categories: { type: Array, required: true },
  icon: { type: String, required: true },
  headerImage: { type: String, required: true },
  screenshots: { type: Array, required: true },
  video: { type: String, required: true },
  videoImage: { type: String, required: true },
  previewVideo: { type: String, required: true },
  contentRating: { type: String, required: true },
  contentRatingDescription: { type: String, required: true },
  adSupported: { type: Boolean, required: true },
  released: { type: String, required: true },
  updated: { type: Number, required: true },
  version: { type: String, required: true },
  recentChanges: { type: String, required: true },
  comments: { type: Array, required: true },
  preregister: { type: Boolean, required: true },
  earlyAccessEnabled: { type: Boolean, required: true },
  isAvailableInPlayPass: { type: Boolean, required: true },
  appId: { type: String, required: true, unique: true },
  url: { type: String, required: true },
});

const AppDetails = mongoose.model("AppDetails", appDetailsSchema);

module.exports = AppDetails ;
