const mongoose = require('mongoose');

const appSchema = new mongoose.Schema({
  title: { type: String, required: false },
  description: { type: String, required: false },
  descriptionHTML: { type: String, required: false },
  summary: { type: String, required: false },
  installs: { type: String, required: false },
  minInstalls: { type: Number, required: false },
  maxInstalls: { type: Number, required: false },
  score: { type: Number, required: false },
  scoreText: { type: String, required: false },
  ratings: { type: Number, required: false },
  reviews: { type: Number, required: false },
  histogram: { type: Object, required: false },
  price: { type: Number, required: false },
  free: { type: Boolean, required: false },
  currency: { type: String, required: false },
  priceText: { type: String, required: false },
  available: { type: Boolean, required: false },
  offersIAP: { type: Boolean, required: false },
  IAPRange: { type: String, required: false },
  androidVersion: { type: String, required: false },
  androidVersionText: { type: String, required: false },
  androidMaxVersion: { type: String, required: false },
  developer: { type: String, required: false },
  developerId: { type: String, required: false },
  developerEmail: { type: String, required: false },
  developerWebsite: { type: String, required: false },
  developerAddress: { type: String, required: false },
  privacyPolicy: { type: String, required: false },
  developerInternalID: { type: String, required: false },
  genre: { type: String, required: false },
  genreId: { type: String, required: false },
  categories: { type: Array, required: false },
  icon: { type: String, required: false },
  headerImage: { type: String, required: false },
  screenshots: { type: Array, required: false },
  video: { type: String, required: false },
  videoImage: { type: String, required: false },
  previewVideo: { type: String, required: false },
  contentRating: { type: String, required: false },
  contentRatingDescription: { type: String, required: false },
  adSupported: { type: Boolean, required: false },
  released: { type: String, required: false },
  updated: { type: Number, required: false },
  version: { type: String, required: false },
  recentChanges: { type: String, required: false },
  comments: { type: Array, required: false },
  preregister: { type: Boolean, required: false },
  earlyAccessEnabled: { type: Boolean, required: false },
  isAvailableInPlayPass: { type: Boolean, required: false },
  appId: { type: String, required: false, unique: false },
  url: { type: String, required: false },
});

const App = mongoose.model('App', appSchema);

module.exports = App;
